### ISSUE TITLE
Cannot use staticmatic templates from sinatra app

### ISSUE THREAD

**Issue by volkanunsal** [nex3/dynamicmatic#1]
Just getting around to using Dynamicmatic for an app I'm building. But it will not allow me to use the staticmatic layout, application.haml, for the dynamic pages. This is what my sinatra app looks like:

```
require 'sinatra'
require 'sinatra/dynamicmatic'
staticmatic.run("build")

get '/' do
    haml :test
end 
```

I have a test.haml in my views directory, which is rendered without any layout. I'm not sure if there is something else that needs to be done for this to work properly?

**Comment by nex3** [comment]
Sorry for the long response time - I've been buried in schoolwork this past week.

I can't reproduce this. Are you sure you're using a recent enough version of Sinatra? It needs to be version 0.10.1, which is currently unreleased. You'll need to install it from [the git repo](http://github.com/sinatra/sinatra).

**Comment by volkanunsal** [comment]
My bad. I realized I was using the version 0.0.3. However, now there is another problem when I am raking the version 0.1.0. Here is the complete backtrace from rake install command:

**snipped and removed to Gist**

http://gist.github.com/255721

**Comment by nex3** [comment]
You need the Sinatra 0.10.1 gem. You'll need to install it from [the git repo](http://github.com/sinatra/sinatra).

**Comment by volkanunsal** [comment]
That's the weird part. I do have it. It appears in the gem list: 

...rkspace\Xperiments\Sinatra> gem list sinatra

**\* LOCAL GEMS ***

sinatra (0.9.4)

sinatra-sinatra (0.10.1)

**Comment by nex3** [comment]
sinatra-sinatra isn't the same as plain old sinatra. I stopped depending on the GitHub gem because it's being phased out. You really will need to install from the repo.

**Comment by volkanunsal** [comment]
oh, ok. I have had some difficulty installing sinatra from repo in the past. It may not be optimized for Windows or something. Rake install always fails. And it failed again just now with this error.

gem install pkg/sinatra-0.10.1.gem

Successfully installed sinatra-0.10.1

1 gem installed

Installing ri documentation for sinatra-0.10.1...

File not found: lib

rake aborted!

Command failed with status (1): [gem install pkg/sinatra-0.10.1.gem...]

 But I guess I'll take that question to the Sinatra community. You've been very helpful; I hope to be able to use Dynamicmatic one day.

**Comment by nex3** [comment]
It looks like that only failed when installing the documentation, rather than the gem itself. Does 0.10.1 show up when you do a gem list now?

**Comment by volkanunsal** [comment]
Yes, but it didn't really install the gem either. The gem folder in the gems directory is completely empty except for the README.rdoc and LICENSE files. :-/

**Comment by nex3** [comment]
Oh, too bad. That does sound like a Sinatra issue.

If you want to use it in the meantime, you could always just vendor both dynamicmatic and sinatra.
